## OPENCV PRACTICE

This is for opencv library practice note
- Image
- Shape
- Video
- Basic oprations

### Image 

In [3]:
import cv2
import numpy as np

In [4]:
img = cv2.imread('lena.jpg',1)

In [5]:
print(img)

[[[128 138 225]
  [127 137 224]
  [126 136 224]
  ...
  [126 145 236]
  [110 129 220]
  [ 86 104 197]]

 [[127 137 224]
  [127 137 224]
  [127 137 224]
  ...
  [130 150 235]
  [112 132 217]
  [ 83 102 189]]

 [[127 137 224]
  [127 137 224]
  [128 138 225]
  ...
  [127 148 230]
  [112 133 215]
  [ 85 105 190]]

 ...

 [[ 55  21  82]
  [ 54  20  81]
  [ 62  28  92]
  ...
  [ 82  71 175]
  [ 78  68 175]
  [ 74  65 175]]

 [[ 55  18  80]
  [ 56  19  81]
  [ 66  32  96]
  ...
  [ 82  69 177]
  [ 80  71 181]
  [ 81  72 183]]

 [[ 56  19  81]
  [ 58  21  83]
  [ 68  34  98]
  ...
  [ 81  68 176]
  [ 81  72 183]
  [ 84  74 188]]]


In [8]:
cv2.imshow('Final',img)
k = cv2.waitKey(0)

if k ==27:
    cv2.destroyAllWindows()
elif k == ord('s'):
    cv2.imwrite('lena_copy1.png',img)
    cv2.destroyAllWindows()

True

### Video capture and save

In [ ]:
import cv2
cap=cv2.VideoCapture(0)
print(cap.isOpened())

### Save the frame
fourcc = cv2.VideoWriter_fourcc('X','V','I','D')
out = cv2.VideoWriter('Output.avi',fourcc,20.0,(640,480))

while (cap.isOpened()):
    ret,frame = cap.read() 
    
    if ret == True:
        print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    
        out.write(frame)
        
        gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        cv2.imshow('Video',frame)
    
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break
        
cap.release()
out.release()
cv2.destroyAllWindows()
        
        

True
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0


### OpenCV shape 

In [11]:
import cv2
img = cv2.imread('lena.jpg',1)

img = cv2.line(img,(0,0),(255,255),(255,0,0),2)
img = cv2.arrowedLine(img,(0,255),(255,255),(0,0,255),2)

img = cv2.rectangle(img,(384,0),(510,128),(0,255,0),2)
img = cv2.circle(img,(447,63),63,(0,255,255),-1)

font = cv2.FONT_HERSHEY_SIMPLEX
img = cv2.putText(img,'Opencvddemo',(10,500),font,3,(255,255,255),2,cv2.LINE_AA)

cv2.imshow('Image',img)

cv2.waitKey(0)
cv2.destroyAllWindows()

### Add text to video

In [ ]:
import cv2
import datetime
cap=cv2.VideoCapture(0)
print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
# cap.set(3,600)
# cap.set(4,600)
# print(cap.get(3))
# print(cap.get(4))

while (cap.isOpened()):
    ret,frame = cap.read() 
    
    if ret == True:
        
        font = cv2.FONT_HERSHEY_COMPLEX
        text = 'Width:'+ str(cap.get(3))+'Height'+str(cap.get(4)) 
        date = str(datetime.datetime.now())
        
        frmae = cv2.putText(frame,date,(10,50),font,1,(255,0,0),2,cv2.LINE_AA)
        #gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        cv2.imshow('Video',frame) 
    
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break
        
cap.release()
cv2.destroyAllWindows()

640.0
480.0


### Mouse Event Opencv

In [1]:
import cv2

In [2]:
events = [i for i in dir(cv2) if 'EVENT' in i ]

print(events)

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']


In [6]:
def click_event(event,x,y,flags,param):
    
    ## This is for coorinates
    if event== cv2.EVENT_LBUTTONDOWN:
        print(x,',',y)
        font = cv2.FONT_HERSHEY_COMPLEX
        strxy = str(x) +',' +str(y)
        cv2.putText(img,strxy,(x,y),font,0.5,(255,0,0),1)
        cv2.imshow('image',img)
    
    ## This is for RGB color 
    if event == cv2.EVENT_RBUTTONDOWN:
        blue = img[y,x,0]
        green = img[y,x,1]
        red = img[y,x,2]
        font = cv2.FONT_HERSHEY_COMPLEX
        strBGR = str(blue) +',' +str(green)+','+str(red)
        cv2.putText(img,strBGR,(x,y),font,0.5,(255,0,255),1)
        cv2.imshow('image',img)

In [9]:
import numpy as np 
import cv2

# img = np.zeros((512,512,3),np.uint8)
img = cv2.imread('lena.jpg')
cv2.imshow('image',img)

cv2.setMouseCallback('image',click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()

131 , 25
57 , 164
197 , 309
52 , 230
39 , 296
40 , 368
253 , 474
272 , 188
275 , 55
410 , 51


In [13]:
##### drawable object 

def click_event(event,x,y,flags,param):
    
    ## This is for coorinates
    if event== cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img,(x,y),3,(0,0,255),-1)
        points.append((x,y))
        if len(points)>=2:
            cv2.line(img,points[-1],points[-2],(255,255,0),5)
        cv2.imshow('image',img)
   

In [12]:
import numpy as np 
import cv2

img = np.zeros((512,512,3),np.uint8)
#img = cv2.imread('lena.jpg')
cv2.imshow('image',img)
points=[]
cv2.setMouseCallback('image',click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
### Color showning in new windows

import numpy as np
def click_event(event,x,y,flags,param):
    
    ## This is for coorinates
    if event== cv2.EVENT_LBUTTONDOWN:
        blue = img[x,y,0]
        green = img[x,y,1]
        red = img[x,y,2]
        cv2.circle(img,(x,y),3,(0,255,255),-1)
        mycolorImage = np.zeros((512,512,3),np.uint8)
        
        mycolorImage[:]=[blue,green,red]
        cv2.imshow('colorwindow',mycolorImage)

In [17]:
import numpy as np 
import cv2

# img = np.zeros((512,512,3),np.uint8)
img = cv2.imread('lena.jpg')
cv2.imshow('image',img)

cv2.setMouseCallback('image',click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()

### Basic opration on image

In [30]:
import cv2
img = cv2.imread('messi5.jpg')
img2 = cv2.imread('opencv-logo.png')

print(img.size)
print(img.shape)
print(img.dtype)

b,g,r = cv2.split(img)
img = cv2.merge((b,g,r))

## Copy the ball
ball = img[280:340,330:390]
img[273:333,100:160] = ball

# resize the image
img = cv2.resize(img,(512,512))
img2 =cv2.resize(img2,(512,512))

#two image add opration
#dst=cv2.add(img,img2)

#two image add opration with tranferant 
dst1 = cv2.addWeighted(img,0.8,img2,0.2,0)

#cv2.imshow('image',dst)
cv2.imshow('image',dst1)
cv2.waitKey(0)
cv2.destroyAllWindows()

562248
(342, 548, 3)
uint8
